---
language: python

python:
  - 3.7

install:
  - pip install mypy
  - git clone https://github.com/Shougo/denite.nvim /tmp/denite.nvim

script:
  - SRC=$(find . -name '*.py' | perl -pe 's,^\./,,')
  - export MYPYPATH=/tmp/denite.nvim/rplugin/python3:$MYPYPATH
  - |-
    RESULT=$(
      for i in $SRC; do
        mypy --strict $i | grep "^$i" | tee /dev/tty
      done
    )
  - |-
    if [[ -n $RESULT ]]; then
      exit 1
    fi

notifications:
  slack:
    rooms:
      secure: "I71kBDGV5Y0e1ROvwsy+ZL1qrsovY6hVatOimYY61eAcORVR1yDQX8ZIrc9Hmr25\
               svSzqhO6sKkFD0i9nbVq8Ul67p33SDKpi3L7Whj1aT7zhQjYuiDARAid1t13UCcf\
               sYLkPJIWdHnkevoNU1t/p2oKueiQ6uU42BIne8iq2ChFpfgde9n4JgJOG9MOJOUu\
               JB0f4Bnz8gm1SIvRyqVhbcR/327mN5bTnJrdkrMGYX65dPWw7N1ktea6SIa2EYzz\
               emrN7RjBjfefDKf7OsaQZsKS9fSycRBKjc6vwWwK4cs2sYhbAq8xMJnWpLq36RmH\
               c33MVt7HZSS3zmFwIfBhWGd7HqrUZ3aNu3P7O2oMke3dY+yzC4Tw7ER0urkirx6z\
               5IkcOSz8aSsXFFaiSRrnTXCJVEpTrzFqXV1Ep2eaffLqwxoh/GoLs6VtBYGtoHB7\
               8KvsyzqMa6a7DKDvccqyaDvcBZnh7lXoF4/1Hqez8ZH1/OFzabykXL/1SFT5QE5s\
               6EdPC+KrbDsMTcpee4/Pm9vOwFdZB4Z5lwXvVxWtpWj8SvXrMN8HYjHi8elhCm9X\
               0sRUCpvEZxHKlsVHEUJClQDJRJv4r6uQIw2REmlR/NkV+b+bpBv9RfBCZFHZJgR6\
               eoIYUXidgcjuT4a5nyk1LOYgKYaU1NT6VAJaVHvzYNQ="
    on_success: never
